# Generated by Django 4.0.6 on 2022-08-08 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_user_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[['U', 'Student'], ['S', 'Librarian']], max_length=100),
        ),
    ]
