# Generated by Django 4.0.6 on 2022-08-01 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='borrowed',
            field=models.BooleanField(default=False),
        ),
    ]
